test('hotkey', async () => {
  const page = await browser.newPage()
  await page.goto('http://localhost:4444/hotkey.html')
  await page.keyboard.down('Alt')
  await page.keyboard.press('Space')
  await page.keyboard.up('Alt')
  await expect(page).toMatchElement('.check--toggled')
  await page.keyboard.down('Control')
  await page.keyboard.press('Space')
  await page.keyboard.up('Control')
  await expect(page).not.toMatchElement('.check--toggled')
  await page.keyboard.press('Digit1')
  await expect(page).toMatchElement('.radio-1:checked')
  await page.keyboard.press('Digit2')
  await expect(page).not.toMatchElement('.radio-1:checked')
  await expect(page).toMatchElement('.radio-2:checked')
})
