test('replace', async () => {
  const page = await browser.newPage()
  await page.goto('http://localhost:4444/replace-1.html')
  await expect(page).toClick('a')
  await expect(page).not.toMatch('This is page 1.')
  await expect(page).not.toMatch('This will always be page 1!')
  await expect(page).toMatch('This is page 2.')
  await expect(page).toMatch('This has always been page 2!')
  await expect(page).toMatch('Thank you for your time.')
})
